/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eposassesment;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sam
 */
public class shop extends javax.swing.JFrame {

    /**
     * Creates new form shop
     */
    agents loggedIn = new agents();
    products shoppingCart = new products();
    sales nS = new sales();
    private String username;
    private int userID;
    private boolean permission;
    DefaultListModel shoppingList = new DefaultListModel();
    DecimalFormat DF = new DecimalFormat("#.00");
 

    public shop() {
        initComponents(); 
        lstShoppingCart.setModel(shoppingList);
        loadUserSalesTable();
    }

    public void displayDetails(String username){
        lblUsername.setText(username);
        loggedIn.setUsername(username);
        lblAccountType.setText(loggedIn.accountTypeSearch());
        this.userID = loggedIn.userIDSearch();
        System.out.println(this.userID);
        lblUserID.setText(Integer.toString(this.userID));
        displayUserSalesInfo();
    }
    
    public void accountVerification(String username){
        this.username = username;
        loggedIn.setUsername(username);
        this.permission = loggedIn.permissionSearch();
        btnAddUser.setVisible(this.permission);
        btnAddProduct.setVisible(permission);
        btnDeleteUser.setVisible(permission);
        btnDeleteProduct.setVisible(permission);
        btnUpdateProduct.setVisible(permission);
        checkPermission.setVisible(permission);
    }
    
    public void displaySaleTotal (double sT, double VAT, double t){
        lblSubTotal.setText("£" + DF.format(sT));
        lblVAT.setText("£" + DF.format(VAT));
        lblTotal.setText("£" + DF.format(t));
    }
    
    public void displayUserSalesInfo(){
        System.out.println(this.userID);
        nS.setUserID(this.userID);
        System.out.println(nS.getUserID());
        nS.setuserTotalSales();
        System.out.println(nS.userTotalSales);
        lblHighest.setText(Double.toString(nS.highestSale));
        lblTotalSales.setText(Double.toString(nS.totalSales()));
        lblLowest.setText(Double.toString(nS.lowestSale));
        lblAvg.setText(Double.toString(nS.averageSale));

    }
    
    public void completeSale(){
        int userId = loggedIn.userIDSearch();
        System.out.println(loggedIn.getUserID());
        double total = shoppingCart.total;
        nS.setSalesTotal(total);
        nS.setUserID(userId);
        nS.addSale();
    }
    
    public void loadProductCombo(){
        comboProducts.removeAllItems();
        int rows = 0;
        ResultSet rs = shoppingCart.comboProductLoad();
        
        try {
            while(rs.next()){
                comboProducts.addItem(rs.getString("productName"));
                rows++;
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
        
    }
    
    public void loadUserSalesTable(){
        tblSales.setModel(DbUtils.resultSetToTableModel(nS.RefreshSalesTable()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        mainPain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnBoatShoes = new javax.swing.JButton();
        btnBrogues = new javax.swing.JButton();
        btnCasualShoes = new javax.swing.JButton();
        btnEspadrilles = new javax.swing.JButton();
        btnLoafers = new javax.swing.JButton();
        btnSandals = new javax.swing.JButton();
        btnSmartShoes = new javax.swing.JButton();
        btnTrainers = new javax.swing.JButton();
        btnChelseaBoots = new javax.swing.JButton();
        btnDesertBoots = new javax.swing.JButton();
        btnSlippers = new javax.swing.JButton();
        btnLaces = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        comboProducts = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblHighest = new javax.swing.JLabel();
        lblLowest = new javax.swing.JLabel();
        lblAvg = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        comboUserID = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        txtAccountType = new javax.swing.JTextField();
        checkPermission = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JTextField();
        btnAddUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblProductID = new javax.swing.JLabel();
        comboStockID = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtProductCost = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstShoppingCart = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblVAT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sambury's EPOS System");
        setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N

        btnBoatShoes.setText("Boat Shoes");
        btnBoatShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoatShoesActionPerformed(evt);
            }
        });

        btnBrogues.setText("Brogues");
        btnBrogues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBroguesActionPerformed(evt);
            }
        });

        btnCasualShoes.setText("Casual Shoes");
        btnCasualShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasualShoesActionPerformed(evt);
            }
        });

        btnEspadrilles.setText("Espadrilles");
        btnEspadrilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspadrillesActionPerformed(evt);
            }
        });

        btnLoafers.setText("Loafers");
        btnLoafers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoafersActionPerformed(evt);
            }
        });

        btnSandals.setText("Sandals");
        btnSandals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSandalsActionPerformed(evt);
            }
        });

        btnSmartShoes.setText("Smart Shoes");
        btnSmartShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartShoesActionPerformed(evt);
            }
        });

        btnTrainers.setText("Trainers");
        btnTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainersActionPerformed(evt);
            }
        });

        btnChelseaBoots.setText("Chelsea Boots");
        btnChelseaBoots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChelseaBootsActionPerformed(evt);
            }
        });

        btnDesertBoots.setText("Desert Boots");
        btnDesertBoots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesertBootsActionPerformed(evt);
            }
        });

        btnSlippers.setText("Slippers");
        btnSlippers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlippersActionPerformed(evt);
            }
        });

        btnLaces.setText("laces");
        btnLaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLacesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnChelseaBoots)
                                .addGap(40, 40, 40)
                                .addComponent(btnTrainers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCasualShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDesertBoots, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBrogues, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(btnSandals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLoafers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLaces, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlippers, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEspadrilles, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSmartShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBoatShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSmartShoes)
                        .addComponent(btnBrogues))
                    .addComponent(btnBoatShoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCasualShoes)
                    .addComponent(btnSandals)
                    .addComponent(btnEspadrilles))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoafers)
                    .addComponent(btnSlippers)
                    .addComponent(btnDesertBoots))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChelseaBoots)
                    .addComponent(btnTrainers)
                    .addComponent(btnLaces))
                .addGap(20, 20, 20))
        );

        mainPain.addTab("Products", jPanel1);

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSales);

        btnAdd.setText("Add");

        jLabel2.setText("Highest Sale:");

        jLabel4.setText("Lowest Sale:");

        jLabel6.setText("Average Sale:");

        jLabel8.setText("Total Sales:");

        lblHighest.setText(".....");

        lblLowest.setText(".....");

        lblAvg.setText(".....");

        lblTotalSales.setText(".....");

        loadProductCombo();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalSales)
                            .addComponent(lblAvg)
                            .addComponent(lblLowest)
                            .addComponent(lblHighest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnAdd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblHighest))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblLowest))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblAvg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblTotalSales))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mainPain.addTab("Sales", jPanel2);

        checkPermission.setText("Yes/No");

        btnAddUser.setText("Add");

        btnUpdateUser.setText("Update");

        btnDeleteUser.setText("Delete");

        jLabel10.setText("User ID:");

        jLabel12.setText("Username:");

        jLabel13.setText("Account Type:");

        jLabel14.setText("Password:");

        jLabel15.setText("Admin Permission:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(comboUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAccountType, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(txtUsername))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkPermission))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAddUser)
                                .addGap(34, 34, 34)
                                .addComponent(btnUpdateUser)
                                .addGap(29, 29, 29)
                                .addComponent(btnDeleteUser)))
                        .addGap(120, 120, 120))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(checkPermission))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnDeleteUser))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Users", jPanel5);

        lblProductID.setText("Stock ID:");

        jLabel17.setText("Product:");

        jLabel18.setText("Price:");

        btnAddProduct.setText("Add");

        btnUpdateProduct.setText("Update");

        btnDeleteProduct.setText("Delete");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAddProduct)
                        .addGap(30, 30, 30)
                        .addComponent(btnUpdateProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteProduct))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(lblProductID))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtProductCost, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboStockID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStockID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteProduct)
                    .addComponent(btnUpdateProduct)
                    .addComponent(btnAddProduct))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Products", jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        mainPain.addTab("Admin", jPanel4);

        jScrollPane1.setViewportView(lstShoppingCart);

        jLabel1.setText("Sub Total:");

        lblSubTotal.setText(".....");

        jLabel3.setText("VAT:");

        lblVAT.setText(".....");

        jLabel5.setText("Total:");

        lblTotal.setText(".....");

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        jLabel7.setText("User ID:");

        lblUserID.setText("....");

        jLabel9.setText("Account Type:");

        lblUsername.setText(".....");

        jLabel11.setText("Username:");

        lblAccountType.setText(".....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSignOut)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblUserID)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lblUsername))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lblAccountType)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPain, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotal))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblVAT))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSubTotal)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblUserID)
                            .addComponent(jLabel11)
                            .addComponent(lblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblAccountType)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblSubTotal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lblVAT))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lblTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPain, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnComplete)
                                    .addComponent(btnCancel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnSignOut)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        login log = new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       lstShoppingCart.clearSelection();
       shoppingList.removeAllElements();
       shoppingCart.clearShoppingList();
       lblSubTotal.setText(null);
       lblVAT.setText(null);
       lblTotal.setText(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSmartShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartShoesActionPerformed
        products smartShoes = new products();
        String productName = "Smart Shoes";
        smartShoes.setProductName(productName);
        smartShoes.productPriceSearch();
        double itemCost = smartShoes.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);        
    }//GEN-LAST:event_btnSmartShoesActionPerformed

    private void btnBroguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroguesActionPerformed
        products brogues = new products();
        String productName = "Brogues";
        brogues.setProductName(productName);
        brogues.productPriceSearch();
        double itemCost = brogues.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnBroguesActionPerformed

    private void btnBoatShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoatShoesActionPerformed
        products boatShoes = new products();
        String productName = "Boat Shoes";
        boatShoes.setProductName(productName);
        boatShoes.productPriceSearch();
        double itemCost = boatShoes.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnBoatShoesActionPerformed

    private void btnCasualShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasualShoesActionPerformed
        products casualShoes = new products();
        String productName = "Casual Shoes";
        casualShoes.setProductName(productName);
        casualShoes.productPriceSearch();
        double itemCost = casualShoes.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnCasualShoesActionPerformed

    private void btnSandalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSandalsActionPerformed
        products sandals = new products();
        String productName = "Sandals";
        sandals.setProductName(productName);
        sandals.productPriceSearch();
        double itemCost = sandals.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnSandalsActionPerformed

    private void btnEspadrillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspadrillesActionPerformed
        products espadrilles = new products();
        String productName = "Espadrilles";
        espadrilles.setProductName(productName);
        espadrilles.productPriceSearch();
        double itemCost = espadrilles.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnEspadrillesActionPerformed

    private void btnDesertBootsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesertBootsActionPerformed
        products desertBoots = new products();
        String productName = "Desert Boots";
        desertBoots.setProductName(productName);
        desertBoots.productPriceSearch();
        double itemCost = desertBoots.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnDesertBootsActionPerformed

    private void btnLoafersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoafersActionPerformed
        products loafers = new products();
        String productName = "Loafers";
        loafers.setProductName(productName);
        loafers.productPriceSearch();
        double itemCost = loafers.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnLoafersActionPerformed

    private void btnSlippersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlippersActionPerformed
        products slippers = new products();
        String productName = "Slippers";
        slippers.setProductName(productName);
        slippers.productPriceSearch();
        double itemCost = slippers.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnSlippersActionPerformed

    private void btnChelseaBootsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChelseaBootsActionPerformed
        products chelseaBoots = new products();
        String productName = "Chelsea Boots";
        chelseaBoots.setProductName(productName);
        chelseaBoots.productPriceSearch();
        double itemCost = chelseaBoots.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnChelseaBootsActionPerformed

    private void btnTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainersActionPerformed
        products trainers = new products();
        String productName = "Trainers";
        trainers.setProductName(productName);
        trainers.productPriceSearch();
        double itemCost = trainers.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnTrainersActionPerformed

    private void btnLacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLacesActionPerformed
        products laces = new products();
        String productName = "Laces";
        laces.setProductName(productName);
        laces.productPriceSearch();
        double itemCost = laces.getProductCost();
        shoppingCart.addToShoppingList(itemCost);
        double sT = shoppingCart.subTotal();
        double VAT = shoppingCart.VAT();
        double t = shoppingCart.total();
        shoppingList.addElement(productName);
        displaySaleTotal(sT, VAT, t);
    }//GEN-LAST:event_btnLacesActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        completeSale();
        JOptionPane.showMessageDialog(null, "Completed sale your total is £" 
                + DF.format(shoppingCart.total), "Sale", JOptionPane.INFORMATION_MESSAGE);
        lstShoppingCart.clearSelection();
        shoppingList.removeAllElements();
        shoppingCart.clearShoppingList();
        lblSubTotal.setText(null);
        lblVAT.setText(null);
        lblTotal.setText(null);
        
    }//GEN-LAST:event_btnCompleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBoatShoes;
    private javax.swing.JButton btnBrogues;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCasualShoes;
    private javax.swing.JButton btnChelseaBoots;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnDesertBoots;
    private javax.swing.JButton btnEspadrilles;
    private javax.swing.JButton btnLaces;
    private javax.swing.JButton btnLoafers;
    private javax.swing.JButton btnSandals;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSlippers;
    private javax.swing.JButton btnSmartShoes;
    private javax.swing.JButton btnTrainers;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkPermission;
    private javax.swing.JComboBox<String> comboProducts;
    private javax.swing.JComboBox<String> comboStockID;
    private javax.swing.JComboBox<String> comboUserID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblHighest;
    private javax.swing.JLabel lblLowest;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVAT;
    private javax.swing.JList<String> lstShoppingCart;
    private javax.swing.JTabbedPane mainPain;
    private javax.swing.JTable tblSales;
    private javax.swing.JTextField txtAccountType;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtProductCost;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
